apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "my-project.fullname" . }}-pv"
  labels:
    type: nfs
    name: "{{ include "my-project.fullname" . }}-pv"
    {{- include "my-project.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    {{- toYaml .Values.pv.nfs | nindent 4 }}