name: push

on:
  push:
    branches:
    - "main"

jobs:
  build-container:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
         fetch-depth: '0'
      - name: Bump version
        id: bump-version
        uses: anothrNick/github-tag-action@1.40.0
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         WITH_V: true
         DEFAULT_BUMP: minor

      - name: Checkout
        uses: actions/checkout@v1

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
      - name: Test my-project
        continue-on-error: true
        uses: instrumenta/kubeval-action@master
        with: 
         files: ./my-project/templates


      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: .
          branch: main
          linting: off
          charts_url: https://migelalfa.github.io/Project/
          token: ${{ secrets.GITHUB_TOKEN }}
          app_version: ${{ steps.bump-version.outputs.tag }}
          chart_version: ${{ steps.bump-version.outputs.tag }}

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
   
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./doc
          push: true
          tags: migelalfa/wordpress:${{ steps.bump-version.outputs.tag }}

 
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
         SLACK_CHANNEL: migelalfa-it
         SLACK_COLOR: ${{ job.status }}
         SLACK_ICON: https://img.icons8.com/nolan/344/github.png
         SLACK_MESSAGE: 'Project successfully updated'
         SLACK_TITLE: 'job is done!'
         SLACK_USERNAME: kubeval
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}